export default [
    {
      "login": "demirelrecep",
      "id": 35351559,
      "node_id": "MDQ6VXNlcjM1MzUxNTU5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/35351559?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/demirelrecep",
      "html_url": "https://github.com/demirelrecep",
      "followers_url": "https://api.github.com/users/demirelrecep/followers",
      "following_url": "https://api.github.com/users/demirelrecep/following{/other_user}",
      "gists_url": "https://api.github.com/users/demirelrecep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/demirelrecep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/demirelrecep/subscriptions",
      "organizations_url": "https://api.github.com/users/demirelrecep/orgs",
      "repos_url": "https://api.github.com/users/demirelrecep/repos",
      "events_url": "https://api.github.com/users/demirelrecep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/demirelrecep/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "baristtas",
      "id": 50810282,
      "node_id": "MDQ6VXNlcjUwODEwMjgy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/50810282?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/baristtas",
      "html_url": "https://github.com/baristtas",
      "followers_url": "https://api.github.com/users/baristtas/followers",
      "following_url": "https://api.github.com/users/baristtas/following{/other_user}",
      "gists_url": "https://api.github.com/users/baristtas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/baristtas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/baristtas/subscriptions",
      "organizations_url": "https://api.github.com/users/baristtas/orgs",
      "repos_url": "https://api.github.com/users/baristtas/repos",
      "events_url": "https://api.github.com/users/baristtas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/baristtas/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "lleyla",
      "id": 61522689,
      "node_id": "MDQ6VXNlcjYxNTIyNjg5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/61522689?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lleyla",
      "html_url": "https://github.com/lleyla",
      "followers_url": "https://api.github.com/users/lleyla/followers",
      "following_url": "https://api.github.com/users/lleyla/following{/other_user}",
      "gists_url": "https://api.github.com/users/lleyla/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lleyla/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lleyla/subscriptions",
      "organizations_url": "https://api.github.com/users/lleyla/orgs",
      "repos_url": "https://api.github.com/users/lleyla/repos",
      "events_url": "https://api.github.com/users/lleyla/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lleyla/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "gterzierol",
      "id": 6658820,
      "node_id": "MDQ6VXNlcjY2NTg4MjA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6658820?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gterzierol",
      "html_url": "https://github.com/gterzierol",
      "followers_url": "https://api.github.com/users/gterzierol/followers",
      "following_url": "https://api.github.com/users/gterzierol/following{/other_user}",
      "gists_url": "https://api.github.com/users/gterzierol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gterzierol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gterzierol/subscriptions",
      "organizations_url": "https://api.github.com/users/gterzierol/orgs",
      "repos_url": "https://api.github.com/users/gterzierol/repos",
      "events_url": "https://api.github.com/users/gterzierol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gterzierol/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "kerematam",
      "id": 5495509,
      "node_id": "MDQ6VXNlcjU0OTU1MDk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5495509?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kerematam",
      "html_url": "https://github.com/kerematam",
      "followers_url": "https://api.github.com/users/kerematam/followers",
      "following_url": "https://api.github.com/users/kerematam/following{/other_user}",
      "gists_url": "https://api.github.com/users/kerematam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kerematam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kerematam/subscriptions",
      "organizations_url": "https://api.github.com/users/kerematam/orgs",
      "repos_url": "https://api.github.com/users/kerematam/repos",
      "events_url": "https://api.github.com/users/kerematam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kerematam/received_events",
      "type": "User",
      "site_admin": false
    }
  ]