export default [
    {
        "login": "oksuz",
        "id": 1628550,
        "node_id": "MDQ6VXNlcjE2Mjg1NTA=",
        "avatar_url": "https://avatars3.githubusercontent.com/u/1628550?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/oksuz",
        "html_url": "https://github.com/oksuz",
        "followers_url": "https://api.github.com/users/oksuz/followers",
        "following_url": "https://api.github.com/users/oksuz/following{/other_user}",
        "gists_url": "https://api.github.com/users/oksuz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/oksuz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/oksuz/subscriptions",
        "organizations_url": "https://api.github.com/users/oksuz/orgs",
        "repos_url": "https://api.github.com/users/oksuz/repos",
        "events_url": "https://api.github.com/users/oksuz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/oksuz/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "hakanyalcinkaya",
        "id": 3310562,
        "node_id": "MDQ6VXNlcjMzMTA1NjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/3310562?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hakanyalcinkaya",
        "html_url": "https://github.com/hakanyalcinkaya",
        "followers_url": "https://api.github.com/users/hakanyalcinkaya/followers",
        "following_url": "https://api.github.com/users/hakanyalcinkaya/following{/other_user}",
        "gists_url": "https://api.github.com/users/hakanyalcinkaya/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/hakanyalcinkaya/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hakanyalcinkaya/subscriptions",
        "organizations_url": "https://api.github.com/users/hakanyalcinkaya/orgs",
        "repos_url": "https://api.github.com/users/hakanyalcinkaya/repos",
        "events_url": "https://api.github.com/users/hakanyalcinkaya/events{/privacy}",
        "received_events_url": "https://api.github.com/users/hakanyalcinkaya/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "SelmanKahya",
        "id": 3432700,
        "node_id": "MDQ6VXNlcjM0MzI3MDA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/3432700?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/SelmanKahya",
        "html_url": "https://github.com/SelmanKahya",
        "followers_url": "https://api.github.com/users/SelmanKahya/followers",
        "following_url": "https://api.github.com/users/SelmanKahya/following{/other_user}",
        "gists_url": "https://api.github.com/users/SelmanKahya/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/SelmanKahya/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/SelmanKahya/subscriptions",
        "organizations_url": "https://api.github.com/users/SelmanKahya/orgs",
        "repos_url": "https://api.github.com/users/SelmanKahya/repos",
        "events_url": "https://api.github.com/users/SelmanKahya/events{/privacy}",
        "received_events_url": "https://api.github.com/users/SelmanKahya/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "gkandemi",
        "id": 5469995,
        "node_id": "MDQ6VXNlcjU0Njk5OTU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/5469995?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gkandemi",
        "html_url": "https://github.com/gkandemi",
        "followers_url": "https://api.github.com/users/gkandemi/followers",
        "following_url": "https://api.github.com/users/gkandemi/following{/other_user}",
        "gists_url": "https://api.github.com/users/gkandemi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gkandemi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gkandemi/subscriptions",
        "organizations_url": "https://api.github.com/users/gkandemi/orgs",
        "repos_url": "https://api.github.com/users/gkandemi/repos",
        "events_url": "https://api.github.com/users/gkandemi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gkandemi/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "kerematam",
        "id": 5495509,
        "node_id": "MDQ6VXNlcjU0OTU1MDk=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/5495509?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kerematam",
        "html_url": "https://github.com/kerematam",
        "followers_url": "https://api.github.com/users/kerematam/followers",
        "following_url": "https://api.github.com/users/kerematam/following{/other_user}",
        "gists_url": "https://api.github.com/users/kerematam/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kerematam/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kerematam/subscriptions",
        "organizations_url": "https://api.github.com/users/kerematam/orgs",
        "repos_url": "https://api.github.com/users/kerematam/repos",
        "events_url": "https://api.github.com/users/kerematam/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kerematam/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "bradtraversy",
        "id": 5550850,
        "node_id": "MDQ6VXNlcjU1NTA4NTA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/5550850?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bradtraversy",
        "html_url": "https://github.com/bradtraversy",
        "followers_url": "https://api.github.com/users/bradtraversy/followers",
        "following_url": "https://api.github.com/users/bradtraversy/following{/other_user}",
        "gists_url": "https://api.github.com/users/bradtraversy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bradtraversy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bradtraversy/subscriptions",
        "organizations_url": "https://api.github.com/users/bradtraversy/orgs",
        "repos_url": "https://api.github.com/users/bradtraversy/repos",
        "events_url": "https://api.github.com/users/bradtraversy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bradtraversy/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "gterzierol",
        "id": 6658820,
        "node_id": "MDQ6VXNlcjY2NTg4MjA=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/6658820?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gterzierol",
        "html_url": "https://github.com/gterzierol",
        "followers_url": "https://api.github.com/users/gterzierol/followers",
        "following_url": "https://api.github.com/users/gterzierol/following{/other_user}",
        "gists_url": "https://api.github.com/users/gterzierol/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gterzierol/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gterzierol/subscriptions",
        "organizations_url": "https://api.github.com/users/gterzierol/orgs",
        "repos_url": "https://api.github.com/users/gterzierol/repos",
        "events_url": "https://api.github.com/users/gterzierol/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gterzierol/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "omergulcicek",
        "id": 13813170,
        "node_id": "MDQ6VXNlcjEzODEzMTcw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/13813170?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/omergulcicek",
        "html_url": "https://github.com/omergulcicek",
        "followers_url": "https://api.github.com/users/omergulcicek/followers",
        "following_url": "https://api.github.com/users/omergulcicek/following{/other_user}",
        "gists_url": "https://api.github.com/users/omergulcicek/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/omergulcicek/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/omergulcicek/subscriptions",
        "organizations_url": "https://api.github.com/users/omergulcicek/orgs",
        "repos_url": "https://api.github.com/users/omergulcicek/repos",
        "events_url": "https://api.github.com/users/omergulcicek/events{/privacy}",
        "received_events_url": "https://api.github.com/users/omergulcicek/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "sahinzaybak",
        "id": 20779596,
        "node_id": "MDQ6VXNlcjIwNzc5NTk2",
        "avatar_url": "https://avatars3.githubusercontent.com/u/20779596?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sahinzaybak",
        "html_url": "https://github.com/sahinzaybak",
        "followers_url": "https://api.github.com/users/sahinzaybak/followers",
        "following_url": "https://api.github.com/users/sahinzaybak/following{/other_user}",
        "gists_url": "https://api.github.com/users/sahinzaybak/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sahinzaybak/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sahinzaybak/subscriptions",
        "organizations_url": "https://api.github.com/users/sahinzaybak/orgs",
        "repos_url": "https://api.github.com/users/sahinzaybak/repos",
        "events_url": "https://api.github.com/users/sahinzaybak/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sahinzaybak/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "NisanTarhan",
        "id": 26061469,
        "node_id": "MDQ6VXNlcjI2MDYxNDY5",
        "avatar_url": "https://avatars3.githubusercontent.com/u/26061469?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/NisanTarhan",
        "html_url": "https://github.com/NisanTarhan",
        "followers_url": "https://api.github.com/users/NisanTarhan/followers",
        "following_url": "https://api.github.com/users/NisanTarhan/following{/other_user}",
        "gists_url": "https://api.github.com/users/NisanTarhan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/NisanTarhan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/NisanTarhan/subscriptions",
        "organizations_url": "https://api.github.com/users/NisanTarhan/orgs",
        "repos_url": "https://api.github.com/users/NisanTarhan/repos",
        "events_url": "https://api.github.com/users/NisanTarhan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/NisanTarhan/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "demirelrecep",
        "id": 35351559,
        "node_id": "MDQ6VXNlcjM1MzUxNTU5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/35351559?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/demirelrecep",
        "html_url": "https://github.com/demirelrecep",
        "followers_url": "https://api.github.com/users/demirelrecep/followers",
        "following_url": "https://api.github.com/users/demirelrecep/following{/other_user}",
        "gists_url": "https://api.github.com/users/demirelrecep/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/demirelrecep/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/demirelrecep/subscriptions",
        "organizations_url": "https://api.github.com/users/demirelrecep/orgs",
        "repos_url": "https://api.github.com/users/demirelrecep/repos",
        "events_url": "https://api.github.com/users/demirelrecep/events{/privacy}",
        "received_events_url": "https://api.github.com/users/demirelrecep/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "tanerakhan",
        "id": 39294455,
        "node_id": "MDQ6VXNlcjM5Mjk0NDU1",
        "avatar_url": "https://avatars1.githubusercontent.com/u/39294455?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tanerakhan",
        "html_url": "https://github.com/tanerakhan",
        "followers_url": "https://api.github.com/users/tanerakhan/followers",
        "following_url": "https://api.github.com/users/tanerakhan/following{/other_user}",
        "gists_url": "https://api.github.com/users/tanerakhan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tanerakhan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tanerakhan/subscriptions",
        "organizations_url": "https://api.github.com/users/tanerakhan/orgs",
        "repos_url": "https://api.github.com/users/tanerakhan/repos",
        "events_url": "https://api.github.com/users/tanerakhan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tanerakhan/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "eolmez91",
        "id": 45180829,
        "node_id": "MDQ6VXNlcjQ1MTgwODI5",
        "avatar_url": "https://avatars2.githubusercontent.com/u/45180829?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eolmez91",
        "html_url": "https://github.com/eolmez91",
        "followers_url": "https://api.github.com/users/eolmez91/followers",
        "following_url": "https://api.github.com/users/eolmez91/following{/other_user}",
        "gists_url": "https://api.github.com/users/eolmez91/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eolmez91/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eolmez91/subscriptions",
        "organizations_url": "https://api.github.com/users/eolmez91/orgs",
        "repos_url": "https://api.github.com/users/eolmez91/repos",
        "events_url": "https://api.github.com/users/eolmez91/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eolmez91/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "baristtas",
        "id": 50810282,
        "node_id": "MDQ6VXNlcjUwODEwMjgy",
        "avatar_url": "https://avatars3.githubusercontent.com/u/50810282?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/baristtas",
        "html_url": "https://github.com/baristtas",
        "followers_url": "https://api.github.com/users/baristtas/followers",
        "following_url": "https://api.github.com/users/baristtas/following{/other_user}",
        "gists_url": "https://api.github.com/users/baristtas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/baristtas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/baristtas/subscriptions",
        "organizations_url": "https://api.github.com/users/baristtas/orgs",
        "repos_url": "https://api.github.com/users/baristtas/repos",
        "events_url": "https://api.github.com/users/baristtas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/baristtas/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "cagatayguc",
        "id": 54459088,
        "node_id": "MDQ6VXNlcjU0NDU5MDg4",
        "avatar_url": "https://avatars0.githubusercontent.com/u/54459088?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cagatayguc",
        "html_url": "https://github.com/cagatayguc",
        "followers_url": "https://api.github.com/users/cagatayguc/followers",
        "following_url": "https://api.github.com/users/cagatayguc/following{/other_user}",
        "gists_url": "https://api.github.com/users/cagatayguc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cagatayguc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cagatayguc/subscriptions",
        "organizations_url": "https://api.github.com/users/cagatayguc/orgs",
        "repos_url": "https://api.github.com/users/cagatayguc/repos",
        "events_url": "https://api.github.com/users/cagatayguc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cagatayguc/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "lleyla",
        "id": 61522689,
        "node_id": "MDQ6VXNlcjYxNTIyNjg5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/61522689?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lleyla",
        "html_url": "https://github.com/lleyla",
        "followers_url": "https://api.github.com/users/lleyla/followers",
        "following_url": "https://api.github.com/users/lleyla/following{/other_user}",
        "gists_url": "https://api.github.com/users/lleyla/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lleyla/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lleyla/subscriptions",
        "organizations_url": "https://api.github.com/users/lleyla/orgs",
        "repos_url": "https://api.github.com/users/lleyla/repos",
        "events_url": "https://api.github.com/users/lleyla/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lleyla/received_events",
        "type": "User",
        "site_admin": false
    }
]