export default {
    "login": "alican-uver",
    "id": 61279586,
    "node_id": "MDQ6VXNlcjYxMjc5NTg2",
    "avatar_url": "https://avatars1.githubusercontent.com/u/61279586?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/alican-uver",
    "html_url": "https://github.com/alican-uver",
    "followers_url": "https://api.github.com/users/alican-uver/followers",
    "following_url": "https://api.github.com/users/alican-uver/following{/other_user}",
    "gists_url": "https://api.github.com/users/alican-uver/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/alican-uver/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/alican-uver/subscriptions",
    "organizations_url": "https://api.github.com/users/alican-uver/orgs",
    "repos_url": "https://api.github.com/users/alican-uver/repos",
    "events_url": "https://api.github.com/users/alican-uver/events{/privacy}",
    "received_events_url": "https://api.github.com/users/alican-uver/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Alican Uver",
    "company": null,
    "blog": "https://www.alicanuver.com",
    "location": "Turkey",
    "email": null,
    "hireable": null,
    "bio": "Front End Developer.",
    "twitter_username": null,
    "public_repos": 15,
    "public_gists": 0,
    "followers": 5,
    "following": 16,
    "created_at": "2020-02-20T13:12:13Z",
    "updated_at": "2020-07-16T20:45:41Z"
  }